/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as PortailRouteImport } from './routes/portail'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ChoixFormuleRouteImport } from './routes/choix-formule'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortailIndexRouteImport } from './routes/portail.index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as SuiviTokenRouteImport } from './routes/suivi.$token'
import { Route as ConsoleCabinetsRouteImport } from './routes/console.cabinets'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEmployesRouteImport } from './routes/_authenticated/employes'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalculateurRouteImport } from './routes/_authenticated/calculateur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAbonnementRouteImport } from './routes/_authenticated/abonnement'
import { Route as AuthenticatedDossiersIndexRouteImport } from './routes/_authenticated/dossiers/index'
import { Route as PortailDossierIdRouteImport } from './routes/portail.dossier.$id'
import { Route as ApiWebhooksWaveRouteImport } from './routes/api.webhooks.wave'
import { Route as ApiWebhooksKivviRouteImport } from './routes/api.webhooks.kivvi'
import { Route as ApiWebhooksGeniuspayRouteImport } from './routes/api.webhooks.geniuspay'
import { Route as AuthenticatedDossiersNewRouteImport } from './routes/_authenticated/dossiers/new'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers/$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailRoute = PortailRouteImport.update({
  id: '/portail',
  path: '/portail',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoixFormuleRoute = ChoixFormuleRouteImport.update({
  id: '/choix-formule',
  path: '/choix-formule',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailIndexRoute = PortailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortailRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const SuiviTokenRoute = SuiviTokenRouteImport.update({
  id: '/suivi/$token',
  path: '/suivi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleCabinetsRoute = ConsoleCabinetsRouteImport.update({
  id: '/cabinets',
  path: '/cabinets',
  getParentRoute: () => ConsoleRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployesRoute = AuthenticatedEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculateurRoute =
  AuthenticatedCalculateurRouteImport.update({
    id: '/calculateur',
    path: '/calculateur',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbonnementRoute = AuthenticatedAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIndexRoute =
  AuthenticatedDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortailDossierIdRoute = PortailDossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => PortailRoute,
} as any)
const ApiWebhooksWaveRoute = ApiWebhooksWaveRouteImport.update({
  id: '/api/webhooks/wave',
  path: '/api/webhooks/wave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksKivviRoute = ApiWebhooksKivviRouteImport.update({
  id: '/api/webhooks/kivvi',
  path: '/api/webhooks/kivvi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGeniuspayRoute = ApiWebhooksGeniuspayRouteImport.update({
  id: '/api/webhooks/geniuspay',
  path: '/api/webhooks/geniuspay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDossiersNewRoute =
  AuthenticatedDossiersNewRouteImport.update({
    id: '/dossiers/new',
    path: '/dossiers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/choix-formule': typeof ChoixFormuleRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/console': typeof ConsoleRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/portail': typeof PortailRouteWithChildren
  '/reset': typeof ResetRoute
  '/tarifs': typeof TarifsRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calculateur': typeof AuthenticatedCalculateurRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employes': typeof AuthenticatedEmployesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/console/cabinets': typeof ConsoleCabinetsRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/portail/': typeof PortailIndexRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/api/webhooks/geniuspay': typeof ApiWebhooksGeniuspayRoute
  '/api/webhooks/kivvi': typeof ApiWebhooksKivviRoute
  '/api/webhooks/wave': typeof ApiWebhooksWaveRoute
  '/portail/dossier/$id': typeof PortailDossierIdRoute
  '/dossiers/': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/choix-formule': typeof ChoixFormuleRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/invitation': typeof InvitationRoute
  '/reset': typeof ResetRoute
  '/tarifs': typeof TarifsRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calculateur': typeof AuthenticatedCalculateurRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employes': typeof AuthenticatedEmployesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/console/cabinets': typeof ConsoleCabinetsRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/console': typeof ConsoleIndexRoute
  '/portail': typeof PortailIndexRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/api/webhooks/geniuspay': typeof ApiWebhooksGeniuspayRoute
  '/api/webhooks/kivvi': typeof ApiWebhooksKivviRoute
  '/api/webhooks/wave': typeof ApiWebhooksWaveRoute
  '/portail/dossier/$id': typeof PortailDossierIdRoute
  '/dossiers': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/choix-formule': typeof ChoixFormuleRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/console': typeof ConsoleRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/portail': typeof PortailRouteWithChildren
  '/reset': typeof ResetRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/abonnement': typeof AuthenticatedAbonnementRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calculateur': typeof AuthenticatedCalculateurRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/employes': typeof AuthenticatedEmployesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/console/cabinets': typeof ConsoleCabinetsRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/portail/': typeof PortailIndexRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/_authenticated/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/api/webhooks/geniuspay': typeof ApiWebhooksGeniuspayRoute
  '/api/webhooks/kivvi': typeof ApiWebhooksKivviRoute
  '/api/webhooks/wave': typeof ApiWebhooksWaveRoute
  '/portail/dossier/$id': typeof PortailDossierIdRoute
  '/_authenticated/dossiers/': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/choix-formule'
    | '/conditions'
    | '/confidentialite'
    | '/console'
    | '/invitation'
    | '/portail'
    | '/reset'
    | '/tarifs'
    | '/abonnement'
    | '/admin'
    | '/calculateur'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/employes'
    | '/onboarding'
    | '/statistiques'
    | '/console/cabinets'
    | '/suivi/$token'
    | '/console/'
    | '/portail/'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/api/webhooks/geniuspay'
    | '/api/webhooks/kivvi'
    | '/api/webhooks/wave'
    | '/portail/dossier/$id'
    | '/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/choix-formule'
    | '/conditions'
    | '/confidentialite'
    | '/invitation'
    | '/reset'
    | '/tarifs'
    | '/abonnement'
    | '/admin'
    | '/calculateur'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/employes'
    | '/onboarding'
    | '/statistiques'
    | '/console/cabinets'
    | '/suivi/$token'
    | '/console'
    | '/portail'
    | '/dossiers/$id'
    | '/dossiers/new'
    | '/api/webhooks/geniuspay'
    | '/api/webhooks/kivvi'
    | '/api/webhooks/wave'
    | '/portail/dossier/$id'
    | '/dossiers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/choix-formule'
    | '/conditions'
    | '/confidentialite'
    | '/console'
    | '/invitation'
    | '/portail'
    | '/reset'
    | '/tarifs'
    | '/_authenticated/abonnement'
    | '/_authenticated/admin'
    | '/_authenticated/calculateur'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/employes'
    | '/_authenticated/onboarding'
    | '/_authenticated/statistiques'
    | '/console/cabinets'
    | '/suivi/$token'
    | '/console/'
    | '/portail/'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/dossiers/new'
    | '/api/webhooks/geniuspay'
    | '/api/webhooks/kivvi'
    | '/api/webhooks/wave'
    | '/portail/dossier/$id'
    | '/_authenticated/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChoixFormuleRoute: typeof ChoixFormuleRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  InvitationRoute: typeof InvitationRoute
  PortailRoute: typeof PortailRouteWithChildren
  ResetRoute: typeof ResetRoute
  TarifsRoute: typeof TarifsRoute
  SuiviTokenRoute: typeof SuiviTokenRoute
  ApiWebhooksGeniuspayRoute: typeof ApiWebhooksGeniuspayRoute
  ApiWebhooksKivviRoute: typeof ApiWebhooksKivviRoute
  ApiWebhooksWaveRoute: typeof ApiWebhooksWaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail': {
      id: '/portail'
      path: '/portail'
      fullPath: '/portail'
      preLoaderRoute: typeof PortailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choix-formule': {
      id: '/choix-formule'
      path: '/choix-formule'
      fullPath: '/choix-formule'
      preLoaderRoute: typeof ChoixFormuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail/': {
      id: '/portail/'
      path: '/'
      fullPath: '/portail/'
      preLoaderRoute: typeof PortailIndexRouteImport
      parentRoute: typeof PortailRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/suivi/$token': {
      id: '/suivi/$token'
      path: '/suivi/$token'
      fullPath: '/suivi/$token'
      preLoaderRoute: typeof SuiviTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/cabinets': {
      id: '/console/cabinets'
      path: '/cabinets'
      fullPath: '/console/cabinets'
      preLoaderRoute: typeof ConsoleCabinetsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employes': {
      id: '/_authenticated/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof AuthenticatedEmployesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculateur': {
      id: '/_authenticated/calculateur'
      path: '/calculateur'
      fullPath: '/calculateur'
      preLoaderRoute: typeof AuthenticatedCalculateurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abonnement': {
      id: '/_authenticated/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AuthenticatedAbonnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/': {
      id: '/_authenticated/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof AuthenticatedDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portail/dossier/$id': {
      id: '/portail/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/portail/dossier/$id'
      preLoaderRoute: typeof PortailDossierIdRouteImport
      parentRoute: typeof PortailRoute
    }
    '/api/webhooks/wave': {
      id: '/api/webhooks/wave'
      path: '/api/webhooks/wave'
      fullPath: '/api/webhooks/wave'
      preLoaderRoute: typeof ApiWebhooksWaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/kivvi': {
      id: '/api/webhooks/kivvi'
      path: '/api/webhooks/kivvi'
      fullPath: '/api/webhooks/kivvi'
      preLoaderRoute: typeof ApiWebhooksKivviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/geniuspay': {
      id: '/api/webhooks/geniuspay'
      path: '/api/webhooks/geniuspay'
      fullPath: '/api/webhooks/geniuspay'
      preLoaderRoute: typeof ApiWebhooksGeniuspayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dossiers/new': {
      id: '/_authenticated/dossiers/new'
      path: '/dossiers/new'
      fullPath: '/dossiers/new'
      preLoaderRoute: typeof AuthenticatedDossiersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonnementRoute: typeof AuthenticatedAbonnementRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalculateurRoute: typeof AuthenticatedCalculateurRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmployesRoute: typeof AuthenticatedEmployesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRoute
  AuthenticatedDossiersNewRoute: typeof AuthenticatedDossiersNewRoute
  AuthenticatedDossiersIndexRoute: typeof AuthenticatedDossiersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonnementRoute: AuthenticatedAbonnementRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalculateurRoute: AuthenticatedCalculateurRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmployesRoute: AuthenticatedEmployesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRoute,
  AuthenticatedDossiersNewRoute: AuthenticatedDossiersNewRoute,
  AuthenticatedDossiersIndexRoute: AuthenticatedDossiersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsoleRouteChildren {
  ConsoleCabinetsRoute: typeof ConsoleCabinetsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleCabinetsRoute: ConsoleCabinetsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface PortailRouteChildren {
  PortailIndexRoute: typeof PortailIndexRoute
  PortailDossierIdRoute: typeof PortailDossierIdRoute
}

const PortailRouteChildren: PortailRouteChildren = {
  PortailIndexRoute: PortailIndexRoute,
  PortailDossierIdRoute: PortailDossierIdRoute,
}

const PortailRouteWithChildren =
  PortailRoute._addFileChildren(PortailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChoixFormuleRoute: ChoixFormuleRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  InvitationRoute: InvitationRoute,
  PortailRoute: PortailRouteWithChildren,
  ResetRoute: ResetRoute,
  TarifsRoute: TarifsRoute,
  SuiviTokenRoute: SuiviTokenRoute,
  ApiWebhooksGeniuspayRoute: ApiWebhooksGeniuspayRoute,
  ApiWebhooksKivviRoute: ApiWebhooksKivviRoute,
  ApiWebhooksWaveRoute: ApiWebhooksWaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
